image: mono:4.4.0.182

stages:
  - build
  
compile:
    stage: build
    script:
        - nuget restore
        - MONO_IOMAP=case xbuild /t:Build /p:Configuration="Release" /p:Platform="x64" Compiler.sln

image: ruby:2.1

pages:
    script:
        - gem install jekyll
        - jekyll build -d public/
    artifacts:
        paths:
            - public
        only:
            - master
