version: 2
jobs:
  build:
    docker:
      - image: dlanguage/dmd
    steps:
      - checkout
      - run:
          name: Compile
          command: dub build
      - test:
          name: Test
          command: dub test
