version: 2
jobs:
  build:
    docker:
      - image: dlanguage/dmd
    steps:
      - checkout
      - run:
          name: Compile
          command: dub build
  test:
    docker:
      - image: dlanguage/dmd
    steps:
      - checkout
      - run:
          name: Test
          command: dub test
  deployment:
    staging:
     branch: master
      heroku:          
        appname: rosebudcompiler
   
